apiVersion: v2
name: cert-manager-webhook-duckdns
version: 1.2.5
appVersion: v1.2.5
description: A Helm chart for cert manager webhook solver for ACME DNS01 challenge via DuckDNS
home: https://github.com/cobexer/cert-manager-webhook-duckdns
icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
keywords:
  - cert-manager
  - webhook
  - letsencrypt
  - tls
sources:
  - https://github.com/cobexer/cert-manager-webhook-duckdns
maintainers:
  - name: Christoph Obexer
    url: https://github.com/cobexer
